[project]
name = "react-demo-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "certifi>=2025.11.12",
    "google-auth>=2.43.0",
    "requests>=2.32.5",
    "websockets>=15.0.1",
]
